### ISSUE TITLE
npm install -g generator-jaMann won't work

### ISSUE THREAD

**Issue by stmh** [MuschPusch/generator-jaMann#1]
➜  ~  npm install -g generator-jaMann
npm http GET https://registry.npmjs.org/generator-jaMann
npm http 404 https://registry.npmjs.org/generator-jaMann
npm ERR! 404 'generator-jaMann' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 14.1.0
npm ERR! command "/usr/local/Cellar/node/0.10.21/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-jaMann"
npm ERR! cwd /Users/stephan
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/stephan/npm-debug.log
npm ERR! not ok code 0

**Comment by MuschPusch** [comment]
ok please try again

**Comment by MuschPusch** [comment]
ehm... camelcase wasn't allowed:

$ npm install -g generator-jamann
