### ISSUE TITLE
How to Install D8

### ISSUE THREAD

**Issue by d34dman** [MuschPusch/generator-jaMann#10]
- Using `yo jamann` create a normal Drupal setup. This should dowload Drupal 7 into the project.
- Once scaffolding is completed, replace the public folder with Drupal 8
- Now `fab config:mbb docker:run` in the project specific folder.
- visit the project url in the browser and continue installing Drupal 8. The credential for database can be found in fabfile.yaml ( hosts -> mbb -> database ).

**Comment by stmh** [comment]
You can try the develop-branch to install drupal 8. There's a minor bug when installing the database, but should be fixable.

To use the develop branch, download the repository, switch to the develop branch, run `npm install` from inside the folder and `npm link` to use your local installation.

**Comment by stmh** [comment]
Part of release 0.4
