### ISSUE TITLE
D8 Support

### ISSUE THREAD

**Issue by d34dman** [MuschPusch/generator-jaMann#15]
jaMann doesn't seems to support D8 projects yet. Is there any plan to support it?

**Comment by stmh** [comment]
the develop branch should support it, but its a bit outdated -- theres jaMensch in our gitlab as a new draft...

**Comment by stmh** [comment]
here's the link to the jaMensch repository: https://source.factorial.io/shuber/jaMensch which will create a composer based drupal 8 project...

**Comment by d34dman** [comment]
Ok will check that out thanks :)
