### ISSUE TITLE
copyTpl fails

### ISSUE THREAD

**Issue by MuschPusch** [MuschPusch/generator-jaMann#2]
https://github.com/MuschPusch/generator-jaMann/blob/master/app/index.js#L73

@stmh any idea? 

The code get's executed/ validated because it fails when changing name:

{ name: answer.name } 

Right now it fails silently...

**Comment by stmh** [comment]
How can I set up the project locally to have a look into this?

**Comment by stmh** [comment]
Got the jaMann working, copyTpl fails. I've no idea why.

**Comment by stmh** [comment]
copyTpl works now
