### ISSUE TITLE
Wait for sudo input / blocking task

### ISSUE THREAD

**Issue by MuschPusch** [MuschPusch/generator-jaMann#7]
@stmh Any idea how i can wait for the user input?

https://github.com/factorial-io/generator-jaMann/commit/47bcd41036460f7af48379bde2b7d7fcd25d5886

Btw: we don't need to run provision, vagrant hostmanager is enough and more lightweight.

**Comment by stmh** [comment]
please review the feature-branch, I added a solution for this.

**Comment by stmh** [comment]
askFor will ask for your admin-password and provide it to sudo.
