### ISSUE TITLE
Scaffolding should rollback if it is not able to download one or more dependencies

### ISSUE THREAD

**Issue by d34dman** [MuschPusch/generator-jaMann#9]
If one or more dependencies fail to download, the scaffolding should rollback.

Right now the scaffolding gives a success message in the end, irrespective of it was able to complete all the task successfully or not. So if it was not able to download a git repo, it would still give success message. 

Thus, if the user fail to watch the output message from the wizard, then the generated folder would be in corrupted state.

**Comment by stmh** [comment]
the new code should fail early with a meaningful error message
